source = ~/.config/hypr/colors.conf

background {
    monitor =
    path = ~/.config/hypr/current_lock.png
    blur_passes = 2
    blur_size = 5
}

input-field {
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35

    outer_color = $primary
    inner_color = $surface_container
    font_color = $on_surface

    fade_on_empty = false
    position = 0, -20
    halign = center
    valign = center
}
