listener {
    timeout = 180
    on-timeout = ~/.config/hypr/scripts/idle-screen.sh
    on-resume = pkill -f qs
}

listener {
    timeout = 300
    on-timeout = hyprlock
}

listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
