##### TERMINAL #####

set -ga terminal-overrides ",xterm-kitty:Tc"
set -g default-terminal "tmux-256color"

##### PREFIX #####

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

##### MATUGEN FALLBACK COLORS #####

set -gq @thm_bar_bg "#130d07"

set -gq @thm_bg "#19120c"
set -gq @thm_fg "#eee0d5"
set -gq @thm_primary "#fcb974"
set -gq @thm_inverse_primary "#855318"
set -gq @thm_surface_low "#211a14"
set -gq @thm_surface "#261e18"
set -gq @thm_surface_variant "#302921"
set -gq @thm_outline "#50453a"
set -gq @thm_text_variant "#d5c3b5"

##### LOAD MATUGEN #####

source-file ~/.config/tmux/generated.conf

##### TRANSPARENCY #####

set -g status-style "bg=default,fg=#{@thm_fg}"
set -g window-style "bg=default"
set -g window-active-style "bg=default"

##### PANES #####

set -g pane-border-style "fg=#{@thm_outline}"
set -g pane-active-border-style "fg=#{@thm_primary}"

##### STATUS BAR #####

set -g status on
set -g status-position top
set -g status-interval 5
set -g status-justify centre

set -g status-left-length 50
set -g status-right-length 150

##### WINDOW TABS #####

set -g window-status-format \
"#[fg=#{@thm_text_variant}] #I:#W "

set -g window-status-current-format \
"#[fg=#{@thm_primary},bold]󰆍 #I:#W#{?window_zoomed_flag,-󰁌,} "

##### LEFT SIDE #####

set -g status-left \
"#[fg=#{@thm_primary},bold]󱂬 #S "

##### RIGHT SIDE #####

set -g status-right \
"#[fg=#{@thm_text_variant}]#{b:pane_current_path} \
#[fg=#{@thm_primary}] #(git -C #{pane_current_path} branch --show-current 2>/dev/null) \
#[fg=#{@thm_primary}] #(grep 'cpu ' /proc/stat | awk '{u=(\$2+\$4)*100/(\$2+\$4+\$5); printf \"%.0f%%\", u}') \
#[fg=#{@thm_primary}] #(free -h | awk '/Mem:/ {print \$3 \"/\" \$2}')"

##### MOUSE #####

set -g mouse on

##### BETTER SPLITS #####

bind | split-window -h
bind - split-window -v

##### VI MODE #####

setw -g mode-keys vi

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'sainnhe/tmux-fzf'

run '~/.tmux/plugins/tpm/tpm'
##### RELOAD CONFIG #####

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"
